# saved from https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose.yml
# single Kafka container with KRaft (no Zookeeper)
# Tested with Docker Compose version v2.23.3, Ubuntu 22.04
version: '3.5'

networks:
  kafka-tutorials:
    name: kafka-tutorials
    driver: bridge
    #external: true

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    networks:
      - kafka-tutorials
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=O94qfF0pQ4-lNvW65-IeRg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      #change localhost or other ip to allow connection from the other machines
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/tmp/bitnami/kafka

volumes:
  kafka_data:
    driver: local